name: my-churn-project
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: iterative/setup-cml@v1

      - name: prep Env
        run: |
          # Your ML workflow goes here
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python scrpt.py

      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Metrics" > report.md
          awk 'NR%4{print "    " $0}{print ""}' metrics.txt  >> report.md

          echo "## Confusion Matrix" > report.md
          echo "![](./conf_matrix.png)"  >> report.md
          
          cml comment create report.md